version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/appqos_client"
    schedule:
      interval: "daily"
    allow:
      # Only update production dependencies
      - dependency-type: "production"
    # Disable version updates (security updates only)
    open-pull-requests-limit: 0
