version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/appqos_client"
    schedule:
      interval: "daily"
    allow:
      # update production dependencies
      - dependency-type: "production"
    ignore:
      # ignore major version updates
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
